use std::env;
use std::path::PathBuf;
fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string());
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        header: Some(
            r#"/*
 * age-otp C FFI Header
 * Auto-generated by cbindgen. Do not edit manually.
 *
 * Generated from Rust FFI module.
 */"#
                .to_string(),
        ),
        include_guard: Some("AGE_OTP_H".to_string()),
        autogen_warning: Some("// Auto-generated. Do not edit.".to_string()),
        includes: vec![],
        sys_includes: vec!["stdint.h".to_string(), "stddef.h".to_string()],
        no_includes: false,
        cpp_compat: false,
        style: cbindgen::Style::Both,
        tab_width: 4,
        usize_is_size_t: true,
        ..Default::default()
    };
    let out_path = PathBuf::from(&crate_dir).join("clib").join("age-otp.h");
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .with_language(cbindgen::Language::C)
        .with_include_guard("AGE_OTP_H")
        .rename_item("CCharset", "OtpCharset")
        .rename_item("OtpErrorCode", "OtpError")
        .generate()
        .expect("Unable to generate C bindings")
        .write_to_file(&out_path);
    println!("cargo:rerun-if-changed=src/ffi.rs");
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=clib/age-otp.h");
}