/*
 * age-otp C FFI Header
 * Auto-generated by cbindgen. Do not edit manually.
 *
 * Generated from Rust FFI module.
 */

#ifndef AGE_OTP_H
#define AGE_OTP_H

// Auto-generated. Do not edit.

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

#define SEED_LEN 32

#define MIN_CODE_LEN 4

#define MAX_CODE_LEN 64

#define MIN_STEP_SECS 1

#define MAX_STEP_SECS 3600

#define MAX_SKEW_STEPS 10

#endif  /* AGE_OTP_H */
