/*
 * age-otp C FFI Header
 * Auto-generated by cbindgen. Do not edit manually.
 *
 * Generated from Rust FFI module.
 */

#ifndef AGE_OTP_H
#define AGE_OTP_H

// Auto-generated. Do not edit.

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

#define OTP_SEED_LEN 32

#define OTP_MIN_CODE_LEN 4

#define OTP_MAX_CODE_LEN 64

#define OTP_MIN_STEP_SECS 1

#define OTP_MAX_STEP_SECS 3600

#define OTP_MAX_SKEW_STEPS 10

#define OTP_DEFAULT_STEP_SECS 30

#define SEED_LEN 32

#define MIN_CODE_LEN 4

#define MAX_CODE_LEN 64

#define MIN_STEP_SECS 1

#define MAX_STEP_SECS 3600

#define MAX_SKEW_STEPS 10

typedef enum OtpError {
    Ok = 0,
    NullPointer = -1,
    InvalidString = -2,
    InvalidPublicKey = -3,
    EngineCreationFailed = -4,
    GenerationFailed = -5,
    VerificationFailed = -6,
    Expired = -7,
    InvalidParameter = -8,
    HexDecodeFailed = -9,
    LengthMismatch = -10,
    Unknown = -99,
} OtpError;

typedef enum OtpCharset {
    Numeric = 0,
    AlphanumericUpper = 1,
    HexLower = 2,
} OtpCharset;

typedef struct COtpEngine {
    void *_private;
} COtpEngine;

typedef struct COtpCode {
    uint8_t _private[0];
} COtpCode;

typedef struct COtpSeed {
    uint8_t _private[0];
} COtpSeed;

enum OtpError otp_engine_from_public_key(const char *pk, struct COtpEngine **out, char **error);

enum OtpError otp_engine_from_seed_bytes(const uint8_t *seed_bytes,
                                         size_t seed_len,
                                         struct COtpEngine **out,
                                         char **error);

enum OtpError otp_engine_from_seed_hex(const char *hex, struct COtpEngine **out, char **error);

void otp_engine_free(struct COtpEngine *engine);

enum OtpError otp_engine_generate(const struct COtpEngine *engine,
                                  size_t len,
                                  uint64_t time_step,
                                  uint64_t step_secs,
                                  enum OtpCharset charset,
                                  struct COtpCode **out,
                                  char **error);

enum OtpError otp_engine_generate_default(const struct COtpEngine *engine,
                                          size_t len,
                                          uint64_t time_step,
                                          struct COtpCode **out,
                                          char **error);

enum OtpError otp_engine_generate_now(const struct COtpEngine *engine,
                                      size_t len,
                                      struct COtpCode **out,
                                      char **error);

enum OtpError otp_engine_verify(const struct COtpEngine *engine,
                                const struct COtpCode *code,
                                uint64_t time_step,
                                uint64_t ttl,
                                uint64_t step_secs,
                                enum OtpCharset charset,
                                char **error);

enum OtpError otp_engine_verify_default(const struct COtpEngine *engine,
                                        const struct COtpCode *code,
                                        uint64_t time_step,
                                        uint64_t ttl,
                                        char **error);

enum OtpError otp_engine_verify_raw(const struct COtpEngine *engine,
                                    const char *raw,
                                    size_t len,
                                    uint64_t time_step,
                                    uint64_t ttl,
                                    uint64_t step_secs,
                                    enum OtpCharset charset,
                                    char **error);

enum OtpError otp_engine_verify_with_skew(const struct COtpEngine *engine,
                                          const char *raw,
                                          size_t len,
                                          uint64_t time_step,
                                          uint64_t ttl,
                                          uint64_t step_secs,
                                          enum OtpCharset charset,
                                          uint64_t skew_steps,
                                          char **error);

char *otp_engine_seed_hex(const struct COtpEngine *engine);

int32_t otp_engine_seed_bytes(const struct COtpEngine *engine, uint8_t *out_bytes, size_t out_len);

char *otp_code_as_str(const struct COtpCode *code);

uint64_t otp_code_born_at(const struct COtpCode *code);

size_t otp_code_len(const struct COtpCode *code);

int32_t otp_code_is_valid_at(const struct COtpCode *code, uint64_t ts, uint64_t ttl);

struct COtpCode *otp_code_clone(const struct COtpCode *code);

void otp_code_free(struct COtpCode *code);

enum OtpError otp_seed_from_public_key(const char *pk, struct COtpSeed **out, char **error);

enum OtpError otp_seed_from_bytes(const uint8_t *bytes,
                                  size_t len,
                                  struct COtpSeed **out,
                                  char **error);

enum OtpError otp_seed_from_hex(const char *hex, struct COtpSeed **out, char **error);

char *otp_seed_to_hex(const struct COtpSeed *seed);

int32_t otp_seed_to_bytes(const struct COtpSeed *seed, uint8_t *out_bytes, size_t out_len);

struct COtpSeed *otp_seed_clone(const struct COtpSeed *seed);

void otp_seed_free(struct COtpSeed *seed);

void otp_string_free(char *s);

uint64_t otp_now_ts(void);

uint64_t otp_calculate_time_step(uint64_t ts, uint64_t step_secs);

int32_t otp_validate_code(const char *code, size_t expected_len, enum OtpCharset charset);

size_t otp_charset_len(enum OtpCharset charset);

char *otp_version(void);

#endif  /* AGE_OTP_H */
